.github/workflows/nightly.yml, .gitignore, gyro.zzz
also want me to add this to astrolabe? do you want it under MasterQ32 or xq?
=> add gyro packaging

src/gl.zig
https://wiki.libsdl.org/SDL_GL_SetSwapInterval
=> Implement sdl.gl.setSwapInterval

src/wrapper/sdl.zig
adds flag for sensor subsystem, exposes conversion routines via struct functions
=> binding/sdl.zig: update InitFlags wrapper, add wasInit wrapper

src/wrapper/sdl.zig
In particular, AudioDevice, AudioFormat, openAudioDevice,
and helper types AudioSpecRequest, AudioSpecResponse, OpenAudioDeviceAllowedChanges, OpenAudioDeviceOptions, and OpenAudioDeviceResult for a nicer interface to openAudioDevice.
I wasn't sure about "sampling rate" vs "sample rate", it looks like "sampling rate" may be the technically more correct term (more often used on Wikipedia) while "sample rate" is more commonly used everywhere else.
=> wrapper/sdl.zig: add wrappers for parts of the audio subsystem

src/wrapper/sdl.zig
Added wrapper for the useful function SDL_WaitEvent() and some others.
=> Add wrapper for waitEvent(), waitEventTimeout() and pumpEvents()

src/wrapper/sdl.zig
This PR exposes the `SDL_*Cursor*` functions and `SDL_Cursor` in the wrapper.
=> Add cursor to wrapper

src/wrapper/sdl.zig
Wraps mouse events. I adapted some field names be more self-explanatory.
Additionally adapts `MouseState` to make use of the newly-introduced `MouseButtonState` struct (result of function `getMouseState()`).
=> wrapper: add wrappers for Mouse*Event

src/wrapper/sdl.zig
All of them except SDL_JoyDeviceEvent and SDL_ControllerDeviceEvent.
For the axis events, I also included a helper function to return the value normalized between -1 and 1.
=> Add Joy/Controller events

src/wrapper/sdl.zig
also adds `Renderer.getDrawBlendMode`
=> wrapper/sdl.zig: add enum of basic BlendMode-s

src/wrapper/sdl.zig
This PR adds the missing float drawing functions
the Logical Size option to renderer
and get/set Window Postition
=> Float drawing, LogicalSize, and WindowPosition

src/wrapper/sdl.zig
new Window.setMinimumSize
new Renderer.setTarget
Window.getWindowPosition -> Window.getPosition
Window.setWindowPosition -> Window.setPosition
formerly private Texture.Info is now public
=> add Window.setMinimumSize and Renderer.setTarget + misc.

src/binding/sdl.zig, src/wrapper/sdl.zig
binding
-------
add SDL_GetTicks64
wrapper
-------
return type of getTicks usize -> u32
add getTicks64
=> add binding/SDL_GetTicks64 and wrapper/getTicks64

examples/native.zig, examples/wrapper.zig, src/binding/sdl.zig, src/wrapper/sdl.zig
This commit add SDL_RenderGeometry support, which requres SDL's version >= 2.0.18
=> add SDL_RenderGeometry binding and wrapper

src/binding/sdl_image.zig
=> run `zig fmt`

src/wrapper/sdl.zig
add texture scale-mode setter/getter
=> add texture scale-mode setter/getter

src/wrapper/sdl.zig
this could be used as a [documentation test](https://github.com/ziglang/zig/issues/7923) once they get added to zig
=> wrapper: add test for `Color.parse`

src/wrapper/ttf.zig
- TTF wrapper function compile errors fixed.
- Added function to load font from memory.
=> Fix ttf wrapper errors and add fn to load from mem

src/wrapper/gl.zig
1. Added the following wrapper fns:
- `sdl.gl.getProcAddress`
- `sdl.gl.getDrawableSize`
2. Changed `gl.Attribute.doublebuffer` type from usize to bool
=> wrapper: gl additions/fixes

Sdk.zig, build.zig
In my use I wanted to put the build config deeper than root dir. This was the smallest change I could figure out that would let me do this
=> allow user to specify build config path

README.md, build.zig
Also fix some deprecated uses of `std.build`.
=> README: Update to new build API

README.md
=> Update 'addModule' for readme guide build file.

src/wrapper/gl.zig, src/wrapper/image.zig, src/wrapper/sdl.zig, src/wrapper/ttf.zig
Fix the build-in methods to use the new style using result location types.
=> Fix buildins using result location types

build.zig
=> Fixes VulkanWrapperModule not compilen as in #142

src/binding/vulkan.zig, src/wrapper/sdl.zig, src/wrapper/vulkan.zig
I needed Vulkan wrappers, so I added them. I also added a wrapper for SDL_GetWindowID and changed a few bindings to make them more accurate.
=> Primitive Vulkan wrapper functions

examples/wrapper.zig, src/wrapper/sdl.zig
I was missing these in a project I was working on so I added them to the wrapper.
=> add multi-draw functions to wrapper

README.md
=> remove references to Sdk.zig in README

build.zig
=> fix linking ttf

.envrc, flake.lock, flake.nix, src/binding/sdl.zig, src/wrapper/sdl.zig
Fixed the issue with `getWMInfo()` returning invalid data. Added  structure for X11 in `SDL_SysWMInfo.u` .
With your permission I'd like to also add a Nix flake file, this should be useful for anyone wishing to develop on NixOS.
=> Fixed getWMInfo() returning invalid data.

README.md, build.zig
std.Build has changed slightly by zig 0.14, and SDL.zig/build.zig has also some minor changes
=> Update example build file in README.md
