build.zig

If vcpkg is present and the sdl2 package is installed on a Windows system, you only need to run `zig build demo-basic`.
Prerequisites:
1. Install https://github.com/Microsoft/vcpkg
2. Install sdl2 package: `vcpkg install sdl2 --triplet x64-windows`

Windows: add vcpkg paths and install SDL2.dll

---

src/image.zig

The C interface for base SDL is already exposed in lib.zig, this does the same for SDL_image in image.zig

Expose C interface for SDL_image

---

gen_sdl.sh

Running the script against the just-released SDL-2.0.16 resulted in some errors for me, so I added some new substitutions to `gen_sdl.sh`.
(The regenerated bindings are not included, because it seems the previous bindings were generated from Linux, and I didn't want to change that.)
Not sure if these are due to Zig updates, the new SDL version, or me being on Windows, but the new lines shouldn't break anything.
- Added an exception to deleting types ending with `_t` if they span multiple lines (leads to syntax errors otherwise).
- The file contained `NULL` as function arguments in two places, replace those with `null` (it's the first argument in both places, so I didn't try to generalize to anything else yet).
- Some functions referred to `__builtin_bswap{16,32,64}` intrinsics, replace …

update gen_sdl.sh to fix some "zig test"-detected errors

---

src/wrapper/sdl.zig

The `dstrect` argument is a const-pointer input argument, describing the region to render to, and not mutable, see https://wiki.libsdl.org/SDL_RenderCopy .
This was incorrectly changed in 0ccbd2b5 (and I believe the code was silently broken? since the capture was by-value and not mutable either).
On an unrelated note, I was quite surprised that the wrapper changes the argument order of `srcRect` and `dstRect`.
I guess it's trying to go in line with `memcpy`?
A bit annoying when looking at the official reference leads you to writing incorrect code, but I assume it was a conscious decision, whatever the reasoning.

wrapper/sdl.zig: fix pointer mutability in Renderer.copy

---

examples/wrapper.zig
src/wrapper/sdl.zig

Unpacks `c.SDL_KeyboardEvent` into a Zig struct with wrapped `Scancode` and `Keycode` enums.
I opted to leave the `KeyModifierSet` packed, the idea being that we don't generate unnecessary bit-masking code if the user chooses to ignore the modifier state.
But then again, maybe the optimizer would inline and discard that code anyway, so I'm open to change it to a `struct` holding `bool` flags instead, which would be in line with `InitFlags` etc.

wrapper/sdl.zig: nicer KeyboardEvent, add KeyModifierSet and -Bit

---

src/wrapper/sdl.zig

As [documentation](https://wiki.libsdl.org/SDL_WaitEvent) states:
> Returns 1 on success or 0 if there was an error while waiting for events; call SDL_GetError() for more information.
Code untested, but this seems more correct to me.
As for `waitEventTimeout`, [the situation is more dubious](https://wiki.libsdl.org/SDL_WaitEventTimeout):
> This also returns 0 if the timeout elapsed without an event arriving.
I asked upstream (https://github.com/libsdl-org/SDL/issues/5052), the proper fix will depend on the reply to that.
I also adapted the doc comments to include the limitation on the caller thread.
I believe the original "Does not conserve energy" remark is due to a busy-loop polling implementation, which should have been addressed for some platforms some of the time in …

wrapper: fix waitEvent error condition, expand doc comments

---

src/binding/sdl.zig
src/wrapper/sdl.zig

Zig 0.9 changed the 'c_void' keyword to 'anyopaque'.

Update to Zig 0.9

---

src/wrapper/sdl.zig

(with a nicer alias `getKeyboardModifierState`)
Same as #35 , didn't mean to close that one, sorry.

wrapper/sdl.zig add .getModState

---

src/wrapper/sdl.zig

Not `.getClipRect` because that one has a bad interface (returns "an empty rectangle if clipping is disabled").

wrapper/sdl.zig: add `Renderer.setClipRect`

---

src/wrapper/sdl.zig

Fixes `maskForButton`, `setPressed`, and reduces it from translated int size to the number of bits SDL currently defines.

wrapper/sdl.zig: MouseButtonState fixes

---

src/wrapper/sdl.zig

Adds wrapper code for the [SDL_AudioStream](https://wiki.libsdl.org/SDL_AudioStream) and [SDL_MixAudioFormat](https://wiki.libsdl.org/SDL_MixAudioFormat). Let me know if anything should be changed.

Add SDL_AudioStream and SDL_MixAudioFormat wrapper

---

src/binding/sdl_image.zig
src/wrapper/image.zig

Hello, thank you for the zig libraries, I was using the image library and noticed the bindings for loading a image from program memory wasn't available. I added those but left the 'IMG_ReadXPMFromArray' out since I wasn't able to import a XPM file in the right format using zig.
*p.s. sorry for the mangled pr message earlier not sure what went wrong*
```zig
const embed = @embedfile("zero.png");
const rw = SDL.c.SDL_RWFromConstMem(
@ptrCast(*const anyopaque, &embed[0]),
@intCast(c_int, embed.len)) 
orelse return SDL.makeError();
defer _ = SDL.c.SDL_RWclose(rw);
// Using the native resolve function that can pick the right load binding
var surface = SDL.image.c.IMG_Load_RW(rw, 0) orelse return SDL.makeError();
// Specified format, case insensitive:
//var surface = …
```

IMG rwop functions

---

Sdk.zig

Resolves build errors created by ziglang/zig#11557

`std.build.Pkg.path` renamed to `std.build.Pkg.source` in zig master

---

examples/wrapper.zig
src/wrapper/sdl.zig

In SDL if you pass to a window both Vulcan and OpenGL as context, it throws a runtime error. But in zig we can do better by creating enums and giving compile time errors. Not only that, but when we call SDL_Init it makes no sense to initialize no subsystem so we can throw an error.

More error handling

---

src/wrapper/sdl.zig

Previously it technically returned a dangling reference to what could have been a local copy.

wrapper: fix Rectangle.getConstSdlPtr self parameter type

---

src/wrapper/sdl.zig

As noted in SDL commit [507ce36](https://github.com/libsdl-org/SDL/commit/507ce36d807dd409963f59fdf9f51fcc8dd00dcb) ,
the parameters flags and depth are both completely unused.
From what I could find this has been the case since the function's
introduction in commit [d2676c2](https://github.com/libsdl-org/SDL/commit/d2676c2985359dd7e9240b14e3e1f13079f781d2) .
Therefore they should not be exposed to callers,
and given `undefined` values.

wrapper: fix createRgbSurfaceWithFormat arguments

---

src/binding/sdl.zig
src/wrapper/sdl.zig

Note the binding change is a follow-up to recent SDL [PR 5888](https://github.com/libsdl-org/SDL/pull/5888) .

wrap SDL text input functions

---

Sdk.zig

I tried using the bindings in one of my projects and realised that I forgot to link to sdl_ttf. When looking in the sdk code I couldn't find linking to sdl_image so I assumed that I just link to it if I want it. The problem to that approach is the fact that on macOS you have to link to 5 different libraries to use sdl_ttf. If you want I can add a function called linkTtf.

Links to sdl_ttf

---

Sdk.zig

This change ensures `sdkRoot()` is run at comptime, in order to fix a compile error caused by stage2's changes to array concatenation.
Closes #89

Fix building with stage2

---

Sdk.zig

`std.zig.system.NativeTargetInfo.detect` no longer takes an allocator

Update to 0.10.0-dev.3962+69da56b36

---

Sdk.zig

See ziglang/zig@d3d2487
Required to build on `0.10.0-dev.4161+dab5bb924`

addLibPath has been replaced with addLibraryPath

---

Sdk.zig

Update `std.zig.system.NativeTargetInfo.detect` call to reflect the removal of the allocator parameter.

Fix `linkTtf`'s usage of the Native Target Info detection function

---

src/wrapper/sdl.zig

Add copyEx and CopyExF methods to Renderer. To follow the same patterns, I added getSdlPtr and getConstSdlPtr to the Point and PointF types.

Add Renderer.copyEx and Renderer.copyExF

---

src/wrapper/sdl.zig

Added a few basic wrappers for intersection. Used `bool` instead of `SDL_BOOL`, I believe this is a legacy thing from the sdl library. Also couldn't find SDL_BOOL in the bindings.
Also noticed `c_int` is used in the binding structs `Rectangle` etc so I kept the parameters `c_int` instead of making `i32` and casting those in the bindings.

Added wrapper functions for basic intersects.

---

src/wrapper/sdl.zig

Adds wrapper fns for `getButton` and `getAxis`.
Also a small addition to the API to get a normalised axis value

wrapper: add some GameController fns

---

Sdk.zig
build.zig

`Sdk.zig` makes use of `addSharedLibrary` which had it's API changed.
`build.zig` uses a  lot of fns that were either removed or had their API changed.

Respond to Build.zig Breaking Changes

---

Sdk.zig

The Zig master branch has recently changed the type of the `cache_root` field of `std.Build` to be a `std.Build.Cache.Directory`. I'm not familiar with what the caching strategy employed by `Sdk.zig` is, so I don't know if there is a better way to leverage the new `std.Build.Cache` API in `Sdk.zig` - this is just the minimum change I made that got things successfully compiling for me.

Update for std.build.Cache change

---

README.md
build.zig

**Zig Version**
0.11.0-dev.3299+34865d693
**Changes**
- Change `b.install(demo)` calls to `std.Build.installArtifact(b, demo);`
- Update example from using `demo_basic.setTarget(target);` to setting `.target = target` in `b.addExecutable`

fix deprecated functions and update example to use .target instead of setTarget

---

README.md

README.md says "sdk.getWrapperPackage", which is stale and makes it hard to track down what is happening for first-timers

docs: update name of getWrapperModule in README

---

src/wrapper/sdl.zig

This makes multiple function calls look cleaner.
```zig
// compare this (with defaults)
try renderer.setViewport(.{
.width = 1920,
.height = 1080,
});
// to this (without defaults)
try renderer.setViewport(.{
.x = 0,
.y = 0,
.width = 1920,
.height = 1080,
});
```
I see how this could be rejected (less explicit), but I think it's obvious than a `Rectangle` has `.x` and `.y` even without errors, especially if the user read the sources and/or has an LSP setup.

wrapper/sdl: default to 0 for x/y fields of Rectangle

---

build.zig

Currently in a project where I try to link SDL to a `*Compile` provided by zig's new package manager. I get bogus errors like: 
```
error: unable to check cache: stat file 'D:\a\turbo\turbo\zig-cache\C:\Users\runneradmin\AppData\Local\zig\p\1220dbf1d809d07d1910b9853f162458ed1ebc66be81b21ccfc40a2552bc1019f9c2\.build_config\SDL2\lib\libSDL2.dll.a' failed: FileNotFound
```
As far as I'm aware, the file paths listed in `sdl.json` (from `.build_config\`) could very well be absolute and even if they're not (in my case), they don't seem to be that accessible to executables that exist in zig's cache as opposed to the build root. 
By using `.cwd_relative` instead of `.path` when working with `sdk_paths` SDL.zig can link to artifacts from the package manager.

fix: paths to SDL files in .build_config should be .cwd_relative

---

src/binding/sdl_ttf.zig
src/wrapper/ttf.zig

Add support for https://wiki.libsdl.org/SDL2_ttf/TTF_SetFontSize

Add wrapper method to set font size

---

examples/native.zig
src/wrapper/sdl.zig

Following #176, a number of .a = 255 specifications are now redundant, and this pr removes those

remove redundant alpha

---

build.zig

[`std.mem.split` is deprecated](https://ziglang.org/documentation/master/std/#std.mem.split) and doesn't build on Zig master.

build.zig: use splitScalar instead of split

---

.gitignore

The zig compiler emits files to a zig-cache folder, and I don't believe these should be committed to git

add zig-cache to gitignore

---

build.zig

I'm enabling SDL_ttf on Windows and making it easier to add support for other SDL2 modules in the future.
Breaking API changes include changes to the link(...) function, that now has the option to define which SDL2 library to link:
```zig
sdk.link(lib, .dynamic, .SDL2);
sdk.link(lib, .dynamic, .SDL2_ttf);
```
I've tested the code locally in my own project, as well as by running the following on an Apple Silicon computer and Windows 11:
```
zig build run-native
zig build run-wrapper-image
```
I haven't tested on Linux.

Add SDL_ttf Windows support, refactor build file

---

src/binding/sdl.zig
src/wrapper/sdl.zig

* Expose joy battery level event, it is send by more recent SDL2 versions when you have a game controller plugged-in. 
* Expose SDL_IsGameController() as `SDL.GameController.is()
* Add `GameController.instanceId()` to get the joystick instance ID, required to handle controller removed event properly.
* Fix `GameController.nameForIndex()` to return the correct type

GameController wrapper improvements

---

README.md
build.zig

Latest zig build system can't give absolute file path with @src now, hence the deprecation of sdkPath.
Not sure if this is good solution. I'm open to any suggestion.

update to zig 0.14.0-dev.737+30b4a87db, deprecated sdkPath

---

README.md

This commit removes the `linkTtf` function from the README documentation and updates the `link` function.

Update `link` function doc in the README

---

build.zig
build.zig.zon

zig has a built-in package manager, and it's nice if we're able to comply with its requirements.
this file is mostly based on the `gyro.zzz` file already present. 
Tell me if this is somehow incomplete.

add build.zig.zon

---

build.zig.zon

Stubs were missing in the build.zig.zon, without it on the list they were not pulled when you `zig fetch`. Which causes a build failure.
Stubs are needed in the [build.zig](https://github.com/ikskuh/SDL.zig/blob/4e83984a7614ecf781ae0d98717db18fbe53014d/build.zig#L118) with an `@embed`.

include stubs in build.zig.zon

---

src/wrapper/sdl.zig

An unexpected event made my project crash; I have no idea which event it was, but I consider it to be irrelevant: defaulting to `@panic` on unsupported event didn't feel sane to me, crashing projects on upstream API update doesn't seem nice. I decided to return a `unsupported(u32)` value with the raw type in case the user wants to handle it.

don't panic on unsupported event
